KPMG/KPMG.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KPMG.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

KPMG/KPMG.Web/Controllers/TransactionDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KPMG.Web.Controllers
{
    public class TransactionDataController : Controller
    {
        // GET: TransactionData
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Upload()
        {
            return View();
        }
    }
}

KPMG/KPMG.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

KPMG/KPMG.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

KPMG/KPMG.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

KPMG/KPMG.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app ="kpmg.Admin">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Transaction Data List", "Index", "TransactionData")</li>
                    <li>@Html.ActionLink("Upload Data", "Upload", "TransactionData")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")

    @RenderSection("scripts", required: false)
</bodyng-app>
</html>

KPMG/KPMG.Web/Views/Shared/_Pagination.cshtml
<div class="col-md-4 col-sm-6">
    <div class="dataTables_info" id="sample_1_info" role="status" aria-live="polite">
        Showing {{ model.Paging.CurrentPage * model.Paging.ItemsPerPage - model.Paging.ItemsPerPage + 1 }}
        to {{ model.Paging.CurrentPage * model.Paging.ItemsPerPage > model.Paging.TotalItems ? model.Paging.TotalItems : model.Paging.CurrentPage * model.Paging.ItemsPerPage }}
        of {{ model.Paging.TotalItems }} results
    </div>
</div>
<div class="col-md-3 col-sm-6">
    <div class="dataTables_length">
        <label>
            <select ng-model="model.Paging.ItemsPerPage" ng-change="itemPerPageSetPage()" class="form-control input-xsmall input-inline">
                <option value="5">5</option>
                <option value="10">10</option>
                <option value="15">15</option>
                <option value="20">20</option>
            </select> records
        </label>
    </div>
</div>
<div class="col-md-5 col-sm-12">
    <div class="dataTables_paginate paging_bootstrap_full_number">
        <pagination ng-change="paginationSetPage()"
                    total-items="model.Paging.TotalItems"
                    items-per-page="model.Paging.ItemsPerPage"
                    ng-model="model.Paging.CurrentPage"
                    max-size="4" class="" boundary-links="true"
                    previous-text="&lsaquo;"
                    next-text="&rsaquo;"
                    first-text="&laquo;"
                    last-text="&raquo;"></pagination>
    </div>
</div>

KPMG/KPMG.Web/Views/TransactionData/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Transaction Data List</h2>
<div ng-controller="transactionData" ng-init="init()">
    <table class="table table-striped table-bordered table-hover flip-content">
        <thead class="flip-content">
            <tr>
                <th width="6%">

                </th>
                <th width="10%" class="sortable-column" ng-click="sortOrderSetPage('Account')">
                    Account <i class="fa pull-right" ng-class="table.Account"></i>
                </th>
                <th width="40%">
                    Description <i class="fa pull-right" ng-class="table.Description"></i>
                </th>
                <th width="10%" class="sortable-column" ng-click="sortOrderSetPage('CurrencyCode')">
                    Currency Code <i class="fa pull-right" ng-class="table.CurrencyCode"></i>
                </th>
                <th width="10%" class="sortable-column" ng-click="sortOrderSetPage('Amount')">
                    Amount <i class="fa pull-right" ng-class="table.Amount"></i>
                </th>
                <th width="24%">
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            <tr class="odd gradeX" ng-repeat="item in model.TransactionData">
                <td></td>
                <td>
                    {{ item.Account }}
                </td>
                <td>
                    {{ item.Description }}
                </td>
                <td>
                    {{ item.CurrencyCode }}
                </td>
                <td>
                    {{ item.Amount }}
                </td>
                <td>
                    <a class="label label-danger label-sm" href="" ng-click="deleteTransactionData(item)" title="{{ item.Account }}"><i class="fa fa-trash"></i> Delete</a>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="row">
        @Html.Partial("/Views/Shared/_Pagination.cshtml")
    </div>
</div>

@section scripts{
    <script src="/Angular/Controllers/transaction-data-index.js"></script>
}